name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lintcode:
    name: Repository code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run prettier
        run: yarn prettier --check '**/*.{json,md,yml,yaml}'
      - name: Run stylelint
        run: yarn stylelint '**/*.css'
      - name: Run eslint
        run: yarn eslint . --max-warnings 0
      - name: Run typescript server checks
        run: yarn workspace @syncbase/server typecheck
      - name: Run typescript web checks
        run: yarn workspace @syncbase/web typecheck
      - name: Run graphql codegen checks
        run: yarn workspace @syncbase/web codegencheck
      - name: Run editorconfig
        uses: greut/eclint-action@v0
      - name: echo out the repo owner
        run: |
          echo ${{ env.GITHUB_REPOSITORY_OWNER }}
          echo ${{ github.repository_owner }}
          echo $GITHUB_REPOSITORY_OWNER
      - name: if statement
        if: ${{ env.GITHUB_REPOSITORY_OWNER == github.repository_owner }}
        run: echo "true"
      - name: if statement 2
        if: ${{ env.GITHUB_REPOSITORY_OWNER == github.repository_owner }}
        run: echo "true"
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
