name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lintcode:
    name: Repository code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run editorconfig
        uses: greut/eclint-action@v0
      - name: Run prettier
        run: yarn prettier --check '**/*.{json,md,yml,yaml}'
      - name: Run stylelint
        run: yarn stylelint '**/*.css'
      - name: Run eslint
        run: yarn eslint . --max-warnings 0
      - name: Run typescript server checks
        run: yarn workspace @syncbase/server typecheck
      - name: Run typescript web checks
        run: yarn workspace @syncbase/web typecheck
      - name: Run graphql codegen checks
        run: yarn workspace @syncbase/web codegencheck
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Init with no backend config
        run: terraform init -backend=false
      - name: Terraform Validate
        run: terraform validate
